### Sprint I

- Pasar "dteday" a datetime.
- Comprobar "season": Poner bien las estaciones según el mes.
- El asunto del workingday: el workingday significa que no es fin de semana ni vacaciones según el punto de vista de Washington.

**DAILY 19-ENE**: Si el dia no es ni fin de semana ni festivo (según WA), es 1, si no es 0. Lo dejamos como pendiente. para verlo mañana con el calendario.

In [36]:
import pandas as pd
import numpy as np
from datetime import date, datetime

import warnings
warnings.filterwarnings("ignore")

In [37]:
df = pd.read_csv("../datos/bikes.csv", index_col = 0)

- instant: record index
- dteday : date
- season : season (spring, summer, autumn, winter)
- yr : year (0: 2018, 1:2019)
- mnth : month ( 1 to 12)
- holiday : weather day is a holiday or not (extracted from http://dchr.dc.gov/page/holiday-schedule)
- weekday : day of the week
- workingday : if day is neither weekend nor holiday is 1, otherwise is 0.
+ weathersit : 
	- 1: Clear, Few clouds, Partly cloudy, Partly cloudy
	- 2: Mist + Cloudy, Mist + Broken clouds, Mist + Few clouds, Mist
	- 3: Light Snow, Light Rain + Thunderstorm + Scattered clouds, Light Rain + Scattered clouds
	- 4: Heavy Rain + Ice Pallets + Thunderstorm + Mist, Snow + Fog
- temp : temperature in Celsius
- atemp: feeling temperature in Celsius
- hum: humidity
- windspeed: wind speed
- casual: count of casual users
- registered: count of registered users
- cnt: count of total rental bikes including both casual and registered

In [38]:
# Ponemos instant, que es el index del alquiler
df = df.set_index("instant")
df.head()

dteday  season  yr  mnth  holiday  weekday  workingday  \
instant                                                               
1        01-01-2018  spring   0     1        0        6           0   
2        02-01-2018  spring   0     1        0        0           0   
3        03-01-2018  spring   0     1        0        1           1   
4        04-01-2018  spring   0     1        0        2           1   
5        05-01-2018  spring   0     1        0        3           1   

         weathersit       temp     atemp      hum  windspeed  casual  \
instant                                                                
1                 2  14.110847  18.18125  80.5833  10.749882     331   
2                 2  14.902598  17.68695  69.6087  16.652113     131   
3                 1   8.050924   9.47025  43.7273  16.636703     120   
4                 1   8.200000  10.60610  59.0435  10.739832     108   
5                 1   9.305237  11.46350  43.6957  12.522300      82   

         registered   cnt  
instant                    
1               654   985  
2               670   801  
3              1229  1349  
4              1454  1562  
5              1518  1600

In [39]:
df.sample(6)

dteday  season  yr  mnth  holiday  weekday  workingday  \
instant                                                               
539      23-06-2019  autumn   1     6        0        6           0   
45       14-02-2018  spring   0     2        0        1           1   
29       29-01-2018  spring   0     1        0        6           0   
449      25-03-2019  summer   1     3        0        0           0   
86       27-03-2018  summer   0     3        0        0           0   
306      02-11-2018  winter   0    11        0        3           1   

         weathersit       temp     atemp      hum  windspeed  casual  \
instant                                                                
539               1  29.998347  32.63960  53.4583  12.041307    2657   
45                1  17.015000  19.91750  37.5833  27.999836     208   
29                1   8.057402  10.60630  65.1739   9.739455     123   
449               2  17.937500  21.87440  88.0833  14.791925    1532   
86                2  10.374763  12.51695  49.3913  12.348100     472   
306               1  15.477500  19.50665  71.8750   5.500144     370   

         registered   cnt  
instant                    
539            4801  7458  
45             1705  1913  
29              975  1098  
449            3464  4996  
86             1221  1693  
306            3816  4186

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 730 entries, 1 to 730
Data columns (total 15 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   dteday      730 non-null    object 
 1   season      730 non-null    object 
 2   yr          730 non-null    int64  
 3   mnth        730 non-null    int64  
 4   holiday     730 non-null    int64  
 5   weekday     730 non-null    int64  
 6   workingday  730 non-null    int64  
 7   weathersit  730 non-null    int64  
 8   temp        730 non-null    float64
 9   atemp       730 non-null    float64
 10  hum         730 non-null    float64
 11  windspeed   730 non-null    float64
 12  casual      730 non-null    int64  
 13  registered  730 non-null    int64  
 14  cnt         730 non-null    int64  
dtypes: float64(4), int64(9), object(2)
memory usage: 91.2+ KB


In [41]:
df.describe().T

count         mean          std        min          25%  \
yr          730.0     0.500000     0.500343   0.000000     0.000000   
mnth        730.0     6.526027     3.450215   1.000000     4.000000   
holiday     730.0     0.028767     0.167266   0.000000     0.000000   
weekday     730.0     2.997260     2.006161   0.000000     1.000000   
workingday  730.0     0.683562     0.465405   0.000000     0.000000   
weathersit  730.0     1.394521     0.544807   1.000000     1.000000   
temp        730.0    20.319259     7.506729   2.424346    13.811885   
atemp       730.0    23.726322     8.150308   3.953480    16.889713   
hum         730.0    62.765175    14.237589   0.000000    52.000000   
windspeed   730.0    12.763620     5.195841   1.500244     9.041650   
casual      730.0   849.249315   686.479875   2.000000   316.250000   
registered  730.0  3658.757534  1559.758728  20.000000  2502.250000   
cnt         730.0  4508.006849  1936.011647  22.000000  3169.750000   

                    50%          75%          max  
yr             0.500000     1.000000     1.000000  
mnth           7.000000    10.000000    12.000000  
holiday        0.000000     0.000000     1.000000  
weekday        3.000000     5.000000     6.000000  
workingday     1.000000     1.000000     1.000000  
weathersit     1.000000     2.000000     3.000000  
temp          20.465826    26.880615    35.328347  
atemp         24.368225    30.445775    42.044800  
hum           62.625000    72.989575    97.250000  
windspeed     12.125325    15.625589    34.000021  
casual       717.000000  1096.500000  3410.000000  
registered  3664.500000  4783.250000  6946.000000  
cnt         4548.500000  5966.000000  8714.000000

In [42]:
df.duplicated().sum()

0

In [43]:
df.isnull().sum()

dteday        0
season        0
yr            0
mnth          0
holiday       0
weekday       0
workingday    0
weathersit    0
temp          0
atemp         0
hum           0
windspeed     0
casual        0
registered    0
cnt           0
dtype: int64

In [44]:
 # Cambiamos la columna dteday a datetime
df.dteday = pd.to_datetime(df.dteday)

In [45]:
df["season"].unique()

array(['spring', 'summer', 'autumn', 'winter'], dtype=object)

In [46]:
# Como las estaciones no coinciden con la fecha, creamos una función para ponerlo bien
def season_of_date(col):
    year= col.year
    seasons = {'spring': pd.date_range(start= '21-03-' + str(year), end= '20-06-' + str(year) ),
               'summer': pd.date_range(start= '21-06-' + str(year), end= '22-09-' + str(year) ),
               'autumn': pd.date_range(start= '23-09-' + str(year), end= '20-12-' + str(year))}
    if col in seasons['spring']:
        return 'spring'
    if col in seasons['summer']:
        return 'summer'
    if col in seasons['autumn']:
        return 'autumn'
    else:
        return 'winter'

In [47]:
# Pasamos la funcion
df["season"] = df["dteday"].apply(season_of_date)

In [48]:
df.sample(5)

dteday  season  yr  mnth  holiday  weekday  workingday  \
instant                                                              
273     2018-09-30  autumn   0     9        0        5           1   
551     2019-05-07  spring   1     7        0        4           1   
21      2018-01-21  winter   0     1        0        5           1   
635     2019-09-27  autumn   1     9        0        4           1   
235     2018-08-23  summer   0     8        0        2           1   

         weathersit       temp     atemp      hum  windspeed  casual  \
instant                                                                
273               1  23.130847  27.24145  64.7500  13.833825     830   
551               1  33.927500  38.06835  45.7917  12.999943    1405   
21                1   7.277500   7.89165  45.7083  23.667214      75   
635               2  26.650000  30.39875  69.0833   9.000914     751   
235               1  26.274153  30.30335  45.5417   9.833121    1281   

         registered   cnt  
instant                    
273            4372  5202  
551            4836  6241  
21             1468  1543  
635            6642  7393  
235            4614  5895

In [49]:
df["yr"].unique()

array([0, 1])

In [50]:
df["mnth"].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [51]:
df["holiday"].unique()

array([0, 1])

In [52]:
df.columns

Index(['dteday', 'season', 'yr', 'mnth', 'holiday', 'weekday', 'workingday',
       'weathersit', 'temp', 'atemp', 'hum', 'windspeed', 'casual',
       'registered', 'cnt'],
      dtype='object')

In [53]:
df["weekday"].unique()

array([6, 0, 1, 2, 3, 4, 5])

In [54]:
df["workingday"].unique()

array([0, 1])

In [55]:
df["weathersit"].unique() # No tenemos 4 (tormenta, lluvia fuerte....)

array([2, 1, 3])

- 01-01 New Years Day January  1 
- 16-01 Martin Luther King’s Birthday January 16 
- 13-02 Lincolns Birthday February 
- 20-02 President’s Day February 20
- 31-03 Cesar Chavez’ Birthday March 31
- 29-05 Memorial Day May 29
- 04-07 Independence Day July 4
- 05-07 Bloody Thursday July 5
- 28-07 Harry Bridges’ Birthday July 28
- 04-09 Labor Day September 4
- 10-11 Veterans’ Day November 10
- 23-11 Thanksgiving Day November 23
- 24-11 Day After Thanksgiving November 24
- 24-12 Christmas Eve December 24
- 25-12 Christmas Day December 25
- 31-12 New Year’s Eve December 31