### Sprint I

- Pasar "dteday" a datetime.
- Comprobar "season": Poner bien las estaciones según el mes.
- El asunto del workingday: el workingday significa que no es fin de semana ni vacaciones según el punto de vista de Washington.

**DAILY 19-ENE**: Si el dia no es ni fin de semana ni festivo (según WA), es 1, si no es 0. Lo dejamos como pendiente. para verlo mañana con el calendario.

In [288]:
import pandas as pd
import numpy as np
from datetime import date, datetime

import warnings
warnings.filterwarnings("ignore")

In [289]:
df = pd.read_csv("../datos/bikes.csv", index_col = 0)

- instant: record index
- dteday : date
- season : season (spring, summer, autumn, winter)
- yr : year (0: 2018, 1:2019)
- mnth : month ( 1 to 12)
- holiday : weather day is a holiday or not (extracted from http://dchr.dc.gov/page/holiday-schedule)
- weekday : day of the week
- workingday : if day is neither weekend nor holiday is 1, otherwise is 0.
+ weathersit : 
	- 1: Clear, Few clouds, Partly cloudy, Partly cloudy
	- 2: Mist + Cloudy, Mist + Broken clouds, Mist + Few clouds, Mist
	- 3: Light Snow, Light Rain + Thunderstorm + Scattered clouds, Light Rain + Scattered clouds
	- 4: Heavy Rain + Ice Pallets + Thunderstorm + Mist, Snow + Fog
- temp : temperature in Celsius
- atemp: feeling temperature in Celsius
- hum: humidity
- windspeed: wind speed
- casual: count of casual users
- registered: count of registered users
- cnt: count of total rental bikes including both casual and registered

In [290]:
# Ponemos instant, que es el index del alquiler
df = df.set_index("instant")
df.head()

dteday  season  yr  mnth  holiday  weekday  workingday  \
instant                                                               
1        01-01-2018  spring   0     1        0        6           0   
2        02-01-2018  spring   0     1        0        0           0   
3        03-01-2018  spring   0     1        0        1           1   
4        04-01-2018  spring   0     1        0        2           1   
5        05-01-2018  spring   0     1        0        3           1   

         weathersit       temp     atemp      hum  windspeed  casual  \
instant                                                                
1                 2  14.110847  18.18125  80.5833  10.749882     331   
2                 2  14.902598  17.68695  69.6087  16.652113     131   
3                 1   8.050924   9.47025  43.7273  16.636703     120   
4                 1   8.200000  10.60610  59.0435  10.739832     108   
5                 1   9.305237  11.46350  43.6957  12.522300      82   

         registered   cnt  
instant                    
1               654   985  
2               670   801  
3              1229  1349  
4              1454  1562  
5              1518  1600

In [291]:
lista_holiday = ["01-01-2018", "16-01-2018", "20-02-2018", "31-03-2018", "29-05-2018", "04-07-2018", "05-07-2018", "28-07-2018", "04-09-2018", "10-11-2018", "23-11-2018", "24-11-2018", "24-12-2018", "25-12-2018", "31-12-2018", "01-01-2019", "16-01-2019", "20-02-2019", "31-03-2019", "29-05-2019", "04-07-2019", "05-07-2019", "28-07-2019", "04-09-2019", "10-11-2019", "28-11-2019", "29-11-2019", "24-12-2019", "25-12-2019", "31-12-2019"]

In [292]:
df["holiday"] = df["dteday"].isin(lista_holiday)

In [293]:
df.sample(5)

dteday  season  yr  mnth  holiday  weekday  workingday  \
instant                                                               
287      14-10-2018  winter   0    10    False        5           1   
647      09-10-2019  winter   1    10    False        2           1   
218      06-08-2018  autumn   0     8    False        6           0   
317      13-11-2018  winter   0    11    False        0           0   
187      06-07-2018  autumn   0     7    False        3           1   

         weathersit       temp     atemp      hum  windspeed  casual  \
instant                                                                
287               2  22.584153  26.48375  71.6250  15.000161     529   
647               2  18.313347  21.90560  76.1667  12.750100     601   
218               2  29.383347  33.80770  75.5000  15.292750    1521   
317               1  18.074153  21.52750  45.8333  18.875307    1004   
187               1  29.520000  34.28165  74.3333  10.042161     784   

         registered   cnt  
instant                    
287            3115  3644  
647            5791  6392  
218            2773  4294  
317            2713  3717  
187            3845  4629

In [294]:
df["holiday"] = np.where(df["holiday"] == False, 0, 1)

In [295]:
df.head()

dteday  season  yr  mnth  holiday  weekday  workingday  \
instant                                                               
1        01-01-2018  spring   0     1        1        6           0   
2        02-01-2018  spring   0     1        0        0           0   
3        03-01-2018  spring   0     1        0        1           1   
4        04-01-2018  spring   0     1        0        2           1   
5        05-01-2018  spring   0     1        0        3           1   

         weathersit       temp     atemp      hum  windspeed  casual  \
instant                                                                
1                 2  14.110847  18.18125  80.5833  10.749882     331   
2                 2  14.902598  17.68695  69.6087  16.652113     131   
3                 1   8.050924   9.47025  43.7273  16.636703     120   
4                 1   8.200000  10.60610  59.0435  10.739832     108   
5                 1   9.305237  11.46350  43.6957  12.522300      82   

         registered   cnt  
instant                    
1               654   985  
2               670   801  
3              1229  1349  
4              1454  1562  
5              1518  1600

In [296]:
df = df.drop(columns = ["weekday"], axis = 1)

In [297]:
df.head()

dteday  season  yr  mnth  holiday  workingday  weathersit  \
instant                                                                  
1        01-01-2018  spring   0     1        1           0           2   
2        02-01-2018  spring   0     1        0           0           2   
3        03-01-2018  spring   0     1        0           1           1   
4        04-01-2018  spring   0     1        0           1           1   
5        05-01-2018  spring   0     1        0           1           1   

              temp     atemp      hum  windspeed  casual  registered   cnt  
instant                                                                     
1        14.110847  18.18125  80.5833  10.749882     331         654   985  
2        14.902598  17.68695  69.6087  16.652113     131         670   801  
3         8.050924   9.47025  43.7273  16.636703     120        1229  1349  
4         8.200000  10.60610  59.0435  10.739832     108        1454  1562  
5         9.305237  11.46350  43.6957  12.522300      82        1518  1600

In [298]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 730 entries, 1 to 730
Data columns (total 14 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   dteday      730 non-null    object 
 1   season      730 non-null    object 
 2   yr          730 non-null    int64  
 3   mnth        730 non-null    int64  
 4   holiday     730 non-null    int64  
 5   workingday  730 non-null    int64  
 6   weathersit  730 non-null    int64  
 7   temp        730 non-null    float64
 8   atemp       730 non-null    float64
 9   hum         730 non-null    float64
 10  windspeed   730 non-null    float64
 11  casual      730 non-null    int64  
 12  registered  730 non-null    int64  
 13  cnt         730 non-null    int64  
dtypes: float64(4), int64(8), object(2)
memory usage: 85.5+ KB


In [299]:
df.describe().T

count         mean          std        min          25%  \
yr          730.0     0.500000     0.500343   0.000000     0.000000   
mnth        730.0     6.526027     3.450215   1.000000     4.000000   
holiday     730.0     0.041096     0.198648   0.000000     0.000000   
workingday  730.0     0.683562     0.465405   0.000000     0.000000   
weathersit  730.0     1.394521     0.544807   1.000000     1.000000   
temp        730.0    20.319259     7.506729   2.424346    13.811885   
atemp       730.0    23.726322     8.150308   3.953480    16.889713   
hum         730.0    62.765175    14.237589   0.000000    52.000000   
windspeed   730.0    12.763620     5.195841   1.500244     9.041650   
casual      730.0   849.249315   686.479875   2.000000   316.250000   
registered  730.0  3658.757534  1559.758728  20.000000  2502.250000   
cnt         730.0  4508.006849  1936.011647  22.000000  3169.750000   

                    50%          75%          max  
yr             0.500000     1.000000     1.000000  
mnth           7.000000    10.000000    12.000000  
holiday        0.000000     0.000000     1.000000  
workingday     1.000000     1.000000     1.000000  
weathersit     1.000000     2.000000     3.000000  
temp          20.465826    26.880615    35.328347  
atemp         24.368225    30.445775    42.044800  
hum           62.625000    72.989575    97.250000  
windspeed     12.125325    15.625589    34.000021  
casual       717.000000  1096.500000  3410.000000  
registered  3664.500000  4783.250000  6946.000000  
cnt         4548.500000  5966.000000  8714.000000

In [300]:
df.duplicated().sum()

0

In [301]:
df.isnull().sum()

dteday        0
season        0
yr            0
mnth          0
holiday       0
workingday    0
weathersit    0
temp          0
atemp         0
hum           0
windspeed     0
casual        0
registered    0
cnt           0
dtype: int64

***

### DATETIME

In [302]:
 # Cambiamos la columna dteday a datetime
df.dteday = pd.to_datetime(df.dteday)

In [303]:
df["season"].unique()

array(['spring', 'summer', 'autumn', 'winter'], dtype=object)

In [304]:
# Como las estaciones no coinciden con la fecha, creamos una función para ponerlo bien
def season_of_date(col):
    year= col.year
    seasons = {'spring': pd.date_range(start= '21-03-' + str(year), end= '20-06-' + str(year) ),
               'summer': pd.date_range(start= '21-06-' + str(year), end= '22-09-' + str(year) ),
               'autumn': pd.date_range(start= '23-09-' + str(year), end= '20-12-' + str(year))}
    if col in seasons['spring']:
        return 'spring'
    if col in seasons['summer']:
        return 'summer'
    if col in seasons['autumn']:
        return 'autumn'
    else:
        return 'winter'

In [305]:
# Pasamos la funcion
df["season"] = df["dteday"].apply(season_of_date)

In [306]:
df.sample(5)

dteday  season  yr  mnth  holiday  workingday  weathersit  \
instant                                                                 
216     2018-04-08  spring   0     8        0           1           2   
139     2018-05-19  spring   0     5        0           1           2   
650     2019-12-10  autumn   1    10        0           1           1   
372     2019-07-01  summer   1     1        0           0           1   
174     2018-06-23  summer   0     6        0           1           2   

              temp     atemp      hum  windspeed  casual  registered   cnt  
instant                                                                     
216      29.110000  33.23940  75.7500  13.209050     799        3777  4576  
139      21.764153  25.53710  82.9583   7.250271     735        3840  4575  
650      17.937500  21.65355  53.9167  15.751164    1060        6222  7282  
372      16.126653  19.53895  53.1667  11.708786    1070        3451  4521  
174      29.861653  34.69165  70.3333  15.999868     746        4044  4790

In [307]:
df["weekday"] = df["dteday"].dt.dayofweek 

In [308]:
df["mnth"] = df["dteday"].dt.month

In [309]:

df.head(5)

dteday  season  yr  mnth  holiday  workingday  weathersit  \
instant                                                                 
1       2018-01-01  winter   0     1        1           0           2   
2       2018-02-01  winter   0     2        0           0           2   
3       2018-03-01  winter   0     3        0           1           1   
4       2018-04-01  spring   0     4        0           1           1   
5       2018-05-01  spring   0     5        0           1           1   

              temp     atemp      hum  windspeed  casual  registered   cnt  \
instant                                                                      
1        14.110847  18.18125  80.5833  10.749882     331         654   985   
2        14.902598  17.68695  69.6087  16.652113     131         670   801   
3         8.050924   9.47025  43.7273  16.636703     120        1229  1349   
4         8.200000  10.60610  59.0435  10.739832     108        1454  1562   
5         9.305237  11.46350  43.6957  12.522300      82        1518  1600   

         weekday  
instant           
1              0  
2              3  
3              3  
4              6  
5              1

In [310]:
df["yr"].unique()

array([0, 1])

In [311]:
df["mnth"].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [312]:
df["holiday"].unique()

array([1, 0])

In [313]:
df.columns

Index(['dteday', 'season', 'yr', 'mnth', 'holiday', 'workingday', 'weathersit',
       'temp', 'atemp', 'hum', 'windspeed', 'casual', 'registered', 'cnt',
       'weekday'],
      dtype='object')

In [314]:
df["weekday"].unique()

array([0, 3, 6, 1, 4, 2, 5])

In [315]:
df["workingday"].unique()

array([0, 1])

In [316]:
df["weathersit"].unique() # No tenemos 4 (tormenta, lluvia fuerte....)

array([2, 1, 3])

- 01-01 New Years Day January  1 
- 16-01 Martin Luther King’s Birthday January 16 
- 13-02 Lincolns Birthday February 
- 20-02 President’s Day February 20
- 31-03 Cesar Chavez’ Birthday March 31
- 29-05 Memorial Day May 29
- 04-07 Independence Day July 4
- 05-07 Bloody Thursday July 5
- 28-07 Harry Bridges’ Birthday July 28
- 04-09 Labor Day September 4
- 10-11 Veterans’ Day November 10
- 23-11 Thanksgiving Day November 23
- 24-11 Day After Thanksgiving November 24
- 24-12 Christmas Eve December 24
- 25-12 Christmas Day December 25
- 31-12 New Year’s Eve December 31

In [317]:
df.head(5)

dteday  season  yr  mnth  holiday  workingday  weathersit  \
instant                                                                 
1       2018-01-01  winter   0     1        1           0           2   
2       2018-02-01  winter   0     2        0           0           2   
3       2018-03-01  winter   0     3        0           1           1   
4       2018-04-01  spring   0     4        0           1           1   
5       2018-05-01  spring   0     5        0           1           1   

              temp     atemp      hum  windspeed  casual  registered   cnt  \
instant                                                                      
1        14.110847  18.18125  80.5833  10.749882     331         654   985   
2        14.902598  17.68695  69.6087  16.652113     131         670   801   
3         8.050924   9.47025  43.7273  16.636703     120        1229  1349   
4         8.200000  10.60610  59.0435  10.739832     108        1454  1562   
5         9.305237  11.46350  43.6957  12.522300      82        1518  1600   

         weekday  
instant           
1              0  
2              3  
3              3  
4              6  
5              1

In [318]:
df["weekday"] = df["weekday"] + 1

In [319]:
df.head()

dteday  season  yr  mnth  holiday  workingday  weathersit  \
instant                                                                 
1       2018-01-01  winter   0     1        1           0           2   
2       2018-02-01  winter   0     2        0           0           2   
3       2018-03-01  winter   0     3        0           1           1   
4       2018-04-01  spring   0     4        0           1           1   
5       2018-05-01  spring   0     5        0           1           1   

              temp     atemp      hum  windspeed  casual  registered   cnt  \
instant                                                                      
1        14.110847  18.18125  80.5833  10.749882     331         654   985   
2        14.902598  17.68695  69.6087  16.652113     131         670   801   
3         8.050924   9.47025  43.7273  16.636703     120        1229  1349   
4         8.200000  10.60610  59.0435  10.739832     108        1454  1562   
5         9.305237  11.46350  43.6957  12.522300      82        1518  1600   

         weekday  
instant           
1              1  
2              4  
3              4  
4              7  
5              2

In [320]:
def workingday(col1, col2):
    if col1 == 1 or col2 == 6 or col2 == 7:
        return 0
    else:
        return 1

In [321]:
df["workingday"] = df.apply(lambda col: workingday(col["holiday"], col["weekday"]), axis = 1)

In [322]:
df.sample(6)

dteday  season  yr  mnth  holiday  workingday  weathersit  \
instant                                                                 
385     2019-01-20  winter   1     1        0           0           2   
603     2019-08-26  summer   1     8        0           1           2   
494     2019-09-05  summer   1     9        0           1           2   
405     2019-09-02  summer   1     9        0           1           1   
186     2018-05-07  spring   0     5        1           0           1   
359     2018-12-25  winter   0    12        1           0           1   

              temp     atemp      hum  windspeed  casual  registered   cnt  \
instant                                                                      
385       8.917500  11.04790  45.0000  13.584250     115        3048  3163   
603      26.786653  29.79980  84.5833  15.333486    1483        3772  5255   
494      23.575000  27.65125  74.4167  14.499604     620        4097  4717   
405      10.865000  13.09940  56.2083  13.000479     163        3667  3830   
186      30.613347  34.81690  59.0417   8.459286    1031        3634  4665   
359      11.266103  13.99805  68.1304  10.391097     303         451   754   

         weekday  
instant           
385            7  
603            1  
494            4  
405            1  
186            1  
359            2