### Sprint I

- Pasar "dteday" a datetime.
- Comprobar "season": Poner bien las estaciones según el mes.
- El asunto del workingday: el workingday significa que no es fin de semana ni vacaciones según el punto de vista de Washington.

**DAILY 19-ENE**: Si el dia no es ni fin de semana ni festivo (según WA), es 1, si no es 0. Lo dejamos como pendiente. para verlo mañana con el calendario.

In [139]:
import pandas as pd
import numpy as np
import datetime

In [140]:
df = pd.read_csv("../datos/bikes.csv", index_col = 0)

In [141]:
df.sample(6)

instant      dteday  season  yr  mnth  holiday  weekday  workingday  \
640      641  03-10-2019  winter   1    10        0        3           1   
316      317  13-11-2018  winter   0    11        0        0           0   
356      357  23-12-2018  spring   0    12        0        5           1   
11        12  12-01-2018  spring   0     1        0        3           1   
112      113  23-04-2018  summer   0     4        0        6           0   
641      642  04-10-2019  winter   1    10        0        4           1   

     weathersit       temp     atemp      hum  windspeed  casual  registered  \
640           2  26.957500  29.95665  79.3750   4.458569     728        6844   
316           1  18.074153  21.52750  45.8333  18.875307    1004        2713   
356           1  15.306653  18.87565  68.6250  18.374482     163        2046   
11            1   7.081807   8.02365  59.9545  20.410009      25        1137   
112           2  18.860000  22.50605  88.7917  15.458575    1462        2574   
641           2  26.957500  30.39875  72.2917   7.875582     891        6437   

      cnt  
640  7572  
316  3717  
356  2209  
11   1162  
112  4036  
641  7328

In [142]:
df = df.set_index("instant")
df.head()

dteday  season  yr  mnth  holiday  weekday  workingday  \
instant                                                               
1        01-01-2018  spring   0     1        0        6           0   
2        02-01-2018  spring   0     1        0        0           0   
3        03-01-2018  spring   0     1        0        1           1   
4        04-01-2018  spring   0     1        0        2           1   
5        05-01-2018  spring   0     1        0        3           1   

         weathersit       temp     atemp      hum  windspeed  casual  \
instant                                                                
1                 2  14.110847  18.18125  80.5833  10.749882     331   
2                 2  14.902598  17.68695  69.6087  16.652113     131   
3                 1   8.050924   9.47025  43.7273  16.636703     120   
4                 1   8.200000  10.60610  59.0435  10.739832     108   
5                 1   9.305237  11.46350  43.6957  12.522300      82   

         registered   cnt  
instant                    
1               654   985  
2               670   801  
3              1229  1349  
4              1454  1562  
5              1518  1600

In [143]:
df.head()

dteday  season  yr  mnth  holiday  weekday  workingday  \
instant                                                               
1        01-01-2018  spring   0     1        0        6           0   
2        02-01-2018  spring   0     1        0        0           0   
3        03-01-2018  spring   0     1        0        1           1   
4        04-01-2018  spring   0     1        0        2           1   
5        05-01-2018  spring   0     1        0        3           1   

         weathersit       temp     atemp      hum  windspeed  casual  \
instant                                                                
1                 2  14.110847  18.18125  80.5833  10.749882     331   
2                 2  14.902598  17.68695  69.6087  16.652113     131   
3                 1   8.050924   9.47025  43.7273  16.636703     120   
4                 1   8.200000  10.60610  59.0435  10.739832     108   
5                 1   9.305237  11.46350  43.6957  12.522300      82   

         registered   cnt  
instant                    
1               654   985  
2               670   801  
3              1229  1349  
4              1454  1562  
5              1518  1600

In [144]:
df.describe().T

count         mean          std        min          25%  \
yr          730.0     0.500000     0.500343   0.000000     0.000000   
mnth        730.0     6.526027     3.450215   1.000000     4.000000   
holiday     730.0     0.028767     0.167266   0.000000     0.000000   
weekday     730.0     2.997260     2.006161   0.000000     1.000000   
workingday  730.0     0.683562     0.465405   0.000000     0.000000   
weathersit  730.0     1.394521     0.544807   1.000000     1.000000   
temp        730.0    20.319259     7.506729   2.424346    13.811885   
atemp       730.0    23.726322     8.150308   3.953480    16.889713   
hum         730.0    62.765175    14.237589   0.000000    52.000000   
windspeed   730.0    12.763620     5.195841   1.500244     9.041650   
casual      730.0   849.249315   686.479875   2.000000   316.250000   
registered  730.0  3658.757534  1559.758728  20.000000  2502.250000   
cnt         730.0  4508.006849  1936.011647  22.000000  3169.750000   

                    50%          75%          max  
yr             0.500000     1.000000     1.000000  
mnth           7.000000    10.000000    12.000000  
holiday        0.000000     0.000000     1.000000  
weekday        3.000000     5.000000     6.000000  
workingday     1.000000     1.000000     1.000000  
weathersit     1.000000     2.000000     3.000000  
temp          20.465826    26.880615    35.328347  
atemp         24.368225    30.445775    42.044800  
hum           62.625000    72.989575    97.250000  
windspeed     12.125325    15.625589    34.000021  
casual       717.000000  1096.500000  3410.000000  
registered  3664.500000  4783.250000  6946.000000  
cnt         4548.500000  5966.000000  8714.000000

In [145]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 730 entries, 1 to 730
Data columns (total 15 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   dteday      730 non-null    object 
 1   season      730 non-null    object 
 2   yr          730 non-null    int64  
 3   mnth        730 non-null    int64  
 4   holiday     730 non-null    int64  
 5   weekday     730 non-null    int64  
 6   workingday  730 non-null    int64  
 7   weathersit  730 non-null    int64  
 8   temp        730 non-null    float64
 9   atemp       730 non-null    float64
 10  hum         730 non-null    float64
 11  windspeed   730 non-null    float64
 12  casual      730 non-null    int64  
 13  registered  730 non-null    int64  
 14  cnt         730 non-null    int64  
dtypes: float64(4), int64(9), object(2)
memory usage: 91.2+ KB


In [146]:
df.duplicated().sum()

0

In [147]:
df.isnull().sum()

dteday        0
season        0
yr            0
mnth          0
holiday       0
weekday       0
workingday    0
weathersit    0
temp          0
atemp         0
hum           0
windspeed     0
casual        0
registered    0
cnt           0
dtype: int64

In [148]:
df["season"].unique()

array(['spring', 'summer', 'autumn', 'winter'], dtype=object)

In [149]:
df["yr"].unique()

array([0, 1])

In [150]:
df["mnth"].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [151]:
df["holiday"].unique()

array([0, 1])

In [152]:
df.columns

Index(['dteday', 'season', 'yr', 'mnth', 'holiday', 'weekday', 'workingday',
       'weathersit', 'temp', 'atemp', 'hum', 'windspeed', 'casual',
       'registered', 'cnt'],
      dtype='object')

In [153]:
df["weekday"].unique()

array([6, 0, 1, 2, 3, 4, 5])

In [154]:
df["workingday"].unique()

array([0, 1])

In [155]:
df["weathersit"].unique() # No tenemos 4 (tormenta, lluvia fuerte....)

array([2, 1, 3])

In [156]:
df["temp"].unique()

array([14.110847 , 14.902598 ,  8.050924 ,  8.2      ,  9.305237 ,
        8.378268 ,  8.057402 ,  6.765    ,  5.671653 ,  6.184153 ,
        6.932731 ,  7.081807 ,  6.59567  ,  9.566653 ,  9.498347 ,
        7.209153 ,  8.883347 , 11.979134 , 10.728347 ,  7.2775   ,
        2.4243464,  3.9573897,  3.9930433,  9.162598 ,  8.9175   ,
        7.995    ,  8.342598 ,  8.877402 ,  7.414153 ,  7.879134 ,
       10.66     ,  7.665237 ,  8.663464 , 11.719153 , 11.138347 ,
        9.054153 ,  5.526103 ,  5.918268 ,  7.752731 ,  9.1225   ,
       12.977402 , 17.015    , 10.909567 , 13.048701 , 17.869153 ,
       21.388347 , 16.365847 , 11.693897 , 12.436653 ,  7.471102 ,
        9.091299 , 12.121732 , 14.938268 , 11.5825   , 14.082598 ,
       16.698193 , 10.933347 , 13.735    ,  8.131653 , 15.750847 ,
       15.437402 , 10.731299 , 11.9925   , 12.129153 , 15.952731 ,
       13.495847 , 15.758268 , 13.333897 , 13.013031 , 14.973897 ,
       22.14     , 19.3725   , 13.6325   , 17.647835 , 18.1083

In [157]:
df["atemp"].unique()

array([18.18125 , 17.68695 ,  9.47025 , 10.6061  , 11.4635  , 11.66045 ,
       10.44195 ,  8.1127  ,  5.80875 ,  7.5444  ,  9.5732  ,  8.02365 ,
        7.54415 ,  9.42065 , 12.4056  , 11.71085 ,  8.83855 , 11.61665 ,
       14.9211  , 12.7525  ,  7.89165 ,  3.95348 ,  4.941955,  5.8965  ,
       11.7263  , 10.18    , 10.985   , 11.16585 , 10.6063  , 12.5161  ,
        9.3125  , 11.7265  , 12.72085 ,  8.8939  , 11.42935 , 12.1529  ,
       14.58355 , 15.1829  ,  9.9123  ,  7.21415 ,  7.4774  , 10.67545 ,
       11.6477  , 16.20565 , 19.9175  , 12.7137  , 15.81    , 21.4329  ,
       25.59915 , 19.5702  , 13.8665  , 14.20375 ,  9.30165 , 12.28585 ,
       14.45955 , 17.52305 , 14.1096  , 17.55545 , 20.0059  , 13.19395 ,
       16.00355 , 10.00665 , 12.78395 , 18.93895 , 18.3126  , 11.92305 ,
       15.12    , 14.3304  , 19.2834  , 15.25    , 16.2875  , 19.00455 ,
       16.6     , 15.9089  , 18.3465  , 20.51665 , 26.35045 , 23.32625 ,
       20.48675 , 22.0321  , 16.89695 , 13.54165 , 

In [158]:
df['hum'].unique()

array([80.5833, 69.6087, 43.7273, 59.0435, 43.6957, 51.8261, 49.8696,
       53.5833, 43.4167, 48.2917, 68.6364, 59.9545, 47.0417, 53.7826,
       49.875 , 48.375 , 53.75  , 86.1667, 74.1739, 53.8333, 45.7083,
       40.    , 43.6522, 49.1739, 61.6957, 86.25  , 68.75  , 79.3043,
       65.1739, 72.2174, 60.375 , 82.9565, 77.5417, 43.7826, 58.5217,
       92.9167, 56.8333, 73.8333, 53.7917, 49.4783, 43.7391, 50.6364,
       54.4167, 45.7391, 37.5833, 31.4348, 42.3478, 50.5   , 51.6667,
       18.7917, 40.7826, 60.5   , 57.7778, 42.3043, 69.7391, 71.2174,
       68.    , 87.6364, 53.5   , 44.9583, 31.8333, 61.0417, 78.9167,
       94.8261, 55.1304, 42.0833,  0.    , 64.9565, 59.4583, 52.7391,
       49.6957, 65.5652, 77.6522, 60.2917, 52.5217, 37.9167, 47.375 ,
       73.7391, 62.4583, 83.9565, 49.5   , 39.4167, 49.3913, 30.2174,
       31.4167, 64.6667, 91.8333, 68.625 , 65.375 , 48.    , 42.625 ,
       64.2083, 47.0833, 83.625 , 87.75  , 85.75  , 71.6956, 73.9167,
       81.9167, 54.0

In [159]:
df['windspeed'].unique()

array([10.749882 , 16.652113 , 16.636703 , 10.739832 , 12.5223   ,
        6.0008684, 11.304642 , 17.875868 , 24.25065  , 14.958889 ,
        8.182844 , 20.410009 , 20.167    ,  8.478716 , 10.583521 ,
       12.625011 , 12.999139 ,  9.833925 , 13.957239 , 13.125568 ,
       23.667214 , 11.52199  , 16.5222   , 10.60811  ,  8.696332 ,
       19.68795  ,  7.627079 ,  8.2611   ,  9.739455 ,  4.9568342,
       12.541864 ,  3.565271 , 17.708636 , 18.609384 ,  8.565213 ,
       10.792293 ,  9.5006   ,  3.0423561, 12.652213 , 14.869645 ,
        7.27285  , 13.625589 , 17.479161 , 27.999836 , 19.522058 ,
       16.869997 , 15.416968 , 17.749975 , 34.000021 , 14.956745 ,
       20.625682 , 13.110761 ,  6.305571 , 16.783232 , 23.218113 ,
       12.500257 ,  8.391616 , 19.408962 , 14.500475 , 20.624811 ,
       15.125518 , 13.624182 , 16.875357 , 23.000229 , 22.870584 ,
        8.08355  , 14.75005  , 17.545759 , 15.60899  , 14.791925 ,
       18.130468 ,  9.174042 , 12.348703 , 13.608839 , 14.0417

- 01-01 New Years Day January  1 
- 16-01 Martin Luther King’s Birthday January 16 
- 13-02 Lincolns Birthday February 
- 20-02 President’s Day February 20
- 31-03 Cesar Chavez’ Birthday March 31
- 29-05 Memorial Day May 29
- 04-07 Independence Day July 4
- 05-07 Bloody Thursday July 5
- 28-07 Harry Bridges’ Birthday July 28
- 04-09 Labor Day September 4
- 10-11 Veterans’ Day November 10
- 23-11 Thanksgiving Day November 23
- 24-11 Day After Thanksgiving November 24
- 24-12 Christmas Eve December 24
- 25-12 Christmas Day December 25
- 31-12 New Year’s Eve December 31

Spring: 20-03-2018 20-06-2018
Summer: 21-06-2018 23-09-2018
Autumn

In [177]:
def season_of_date(date_UTC):
    year = str(date_UTC.year)
    time = str(date_UTC.time)
    seasons = {'spring': pd.date_range(start= year +'-03-21' + time, end=year + '-06-20' + time),
               'summer': pd.date_range(start= year + '-06-21' + time, end= year + '-09-22' + time),
               'autumn': pd.date_range(start= year + '-09-23' + time, end= year + '-12-20' + time)}
    if date_UTC in seasons['spring']:
        return 'spring'
    if date_UTC in seasons['summer']:
        return 'summer'
    if date_UTC in seasons['autumn']:
        return 'autumn'
    else:
        return 'winter'

In [ ]:
df["estacion"] = season_of_date(df)

In [ ]:
df["estacion"] = pd.cut(df["dteday"], bins=["21-03-2018"] )